version: '3.8'

services:
  mcp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - UPLOAD_DIR=/app/uploads
    restart: unless-stopped 