package model

// ContentCandidates is a struct that holds content candidates generated by AI
type ContentCandidates struct {
	Titles      []string   // Title candidates (10 patterns)
	ShowNotes   []string   // ShowNote candidates (10 patterns)
	AdTimecodes [][]string // Ad timecode candidates (10 patterns)
}

// SelectedContent is a struct that holds content selected by the user
type SelectedContent struct {
	Title       string   // Selected title
	ShowNote    string   // Selected show note
	AdTimecodes []string // Selected ad timecodes
}
