package model

// ContentCandidates is a struct that holds content candidates generated by AI
type ContentCandidates struct {
	Titles      []string   // Title proposal (single optimal title)
	ShowNotes   []string   // ShowNote proposal (single optimal show note)
}

// SelectedContent is a struct that holds content selected by the user
type SelectedContent struct {
	Title       string   // Selected title
	ShowNote    string   // Selected show note
}
